spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wugithub01/config-repo.git
          username: wugithub01
          password: 136139@wu
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8861
management:
  endpoints:
    web:
      exposure:
        include: "*"